version: "3"

services:
  web:
#   image: git.joinsharkey.org/sharkey/sharkey:latest
    build: .
    restart: always
    links:
      - db
      - redis
#     - meilisearch
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - shonk
    volumes:
      - ./files:/sharkey/files
      - ./cache:/sharkey/cache
      - ./.config:/sharkey/.config:ro

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - shonk
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  db:
    restart: always
    image: postgres:15-alpine
    networks:
      - shonk
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

#  meilisearch:
#    restart: always
#    image: getmeili/meilisearch:v1.3.4
#    environment:
#      - MEILI_NO_ANALYTICS=true
#      - MEILI_ENV=production
#      - MEILI_MASTER_KEY=ChangeThis
#    networks:
#      - shonk
#    volumes:
#      - ./meili_data:/meili_data


networks:
  shonk:
