/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { URL, domainToASCII } from 'node:url';
import { Inject, Injectable } from '@nestjs/common';
import RE2 from 're2';
import psl from 'psl';
import semver from 'semver';
import * as Acct from '@/misc/acct.js';
import { DI } from '@/di-symbols.js';
import type { Config } from '@/config.js';
import { bindThis } from '@/decorators.js';
import type { MiMeta, SoftwareSuspension } from '@/models/Meta.js';
import type { MiInstance } from '@/models/Instance.js';
import type { MiUser, MiLocalUser, MiRemoteUser } from '@/models/User.js';
import { IdentifiableError, errorCodes } from '@/misc/identifiable-error.js';
import { EnvService } from '@/global/EnvService.js';
import { getApId, type IObject } from '@/core/activitypub/type.js';
import { isLocalUser, isRemoteUser } from '@/models/User.js';

export type UriParseResult = {
	/** wether the URI was generated by us */
	local: true;
	/** id in DB */
	id: string;
	/** hint of type, e.g. "notes", "users" */
	type: string;
	/** any remaining text after type and id, not including the slash after id. undefined if empty */
	rest?: string;
} | {
	/** wether the URI was generated by us */
	local: false;
	/** uri in DB */
	uri: string;
};

@Injectable()
export class UtilityService {
	private readonly punyConfigHost: string;

	constructor(
		@Inject(DI.config)
		private config: Config,

		@Inject(DI.meta)
		private meta: MiMeta,

		private readonly envService: EnvService,
	) {
		this.punyConfigHost = this.toPuny(config.host);
	}

	@bindThis
	public getFullApAccount(username: string, host: string | null): string {
		return host ? `${username}@${this.toPuny(host)}` : `${username}@${this.toPuny(this.config.host)}`;
	}

	@bindThis
	public isSelfHost(host: string | null): boolean {
		if (host == null) return true;
		return this.toPuny(this.config.host) === this.toPuny(host);
	}

	@bindThis
	public isUriLocal(uri: string): boolean {
		return this.punyHost(uri) === this.toPuny(this.config.host);
	}

	// メールアドレスのバリデーションを行う
	// https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address
	@bindThis
	public validateEmailFormat(email: string): boolean {
		// Note: replaced MK's complicated regex with a simpler one that is more efficient and reliable.
		const regexp = /^.+@.+$/;
		//const regexp = /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
		return regexp.test(email);
	}

	public isBlockedHost(host: string | null): boolean;
	public isBlockedHost(blockedHosts: string[], host: string | null): boolean;
	@bindThis
	public isBlockedHost(blockedHostsOrHost: string[] | string | null, host?: string | null): boolean {
		const blockedHosts = Array.isArray(blockedHostsOrHost) ? blockedHostsOrHost : this.meta.blockedHosts;
		host = Array.isArray(blockedHostsOrHost) ? host : blockedHostsOrHost;

		if (host == null) return false;
		return blockedHosts.some(x => `.${host.toLowerCase()}`.endsWith(`.${x}`));
	}

	public isSilencedHost(host: string | null): boolean;
	public isSilencedHost(silencedHosts: string[], host: string | null): boolean;
	@bindThis
	public isSilencedHost(silencedHostsOrHost: string[] | string | null, host?: string | null): boolean {
		const silencedHosts = Array.isArray(silencedHostsOrHost) ? silencedHostsOrHost : this.meta.silencedHosts;
		host = Array.isArray(silencedHostsOrHost) ? host : silencedHostsOrHost;

		if (host == null) return false;
		return silencedHosts.some(x => `.${host.toLowerCase()}`.endsWith(`.${x}`));
	}

	public isMediaSilencedHost(host: string | null): boolean;
	public isMediaSilencedHost(silencedHosts: string[], host: string | null): boolean;
	@bindThis
	public isMediaSilencedHost(mediaSilencedHostsOrHost: string[] | string | null, host?: string | null): boolean {
		const mediaSilencedHosts = Array.isArray(mediaSilencedHostsOrHost) ? mediaSilencedHostsOrHost : this.meta.mediaSilencedHosts;
		host = Array.isArray(mediaSilencedHostsOrHost) ? host : mediaSilencedHostsOrHost;

		if (host == null) return false;
		return mediaSilencedHosts.some(x => `.${host.toLowerCase()}`.endsWith(`.${x}`));
	}

	@bindThis
	public isAllowListedHost(host: string | null): boolean {
		if (host == null) return false;
		return this.meta.federationHosts.some(x => `.${host.toLowerCase()}`.endsWith(`.${x}`));
	}

	@bindThis
	public isBubbledHost(host: string | null): boolean {
		if (host == null) return this.meta.bubbleInstances.includes('#local');
		return this.meta.bubbleInstances.some(x => `.${host.toLowerCase()}`.endsWith(`.${x}`));
	}

	@bindThis
	public concatNoteContentsForKeyWordCheck(content: {
		cw?: string | null;
		text?: string | null;
		pollChoices?: string[] | null;
		others?: string[] | null;
	}): string {
		/**
		 * ノートの内容を結合してキーワードチェック用の文字列を生成する
		 * cwとtextは内容が繋がっているかもしれないので間に何も入れずにチェックする
		 */
		return `${content.cw ?? ''}${content.text ?? ''}\n${(content.pollChoices ?? []).join('\n')}\n${(content.others ?? []).join('\n')}`;
	}

	@bindThis
	public isKeyWordIncluded(text: string, keyWords: string[]): boolean {
		if (keyWords.length === 0) return false;
		if (text === '') return false;

		const regexpregexp = /^\/(.+)\/(.*)$/;

		const matched = keyWords.some(filter => {
			// represents RegExp
			const regexp = filter.match(regexpregexp);
			// This should never happen due to input sanitisation.
			if (!regexp) {
				const words = filter.split(' ');
				return words.every(keyword => text.includes(keyword));
			}
			try {
				// TODO: RE2インスタンスをキャッシュ
				return new RE2(regexp[1], regexp[2]).test(text);
			} catch (err) {
				// This should never happen due to input sanitisation.
				return false;
			}
		});

		return matched;
	}

	@bindThis
	public extractDbHost(uri: string): string {
		const url = new URL(uri);
		return this.toPuny(url.host);
	}

	@bindThis
	public toPuny(host: string): string {
		// domainToASCII will return an empty string if we give it a
		// string like `name:123`, but `host` may well be in that form
		// (e.g. when testing locally, you'll get `localhost:3000`); split
		// the port off, and add it back later
		const hostParts = host.toLowerCase().match(/^(.+?)(:.+)?$/);
		if (!hostParts) return '';
		const hostname = hostParts[1];
		const port = hostParts[2] ?? '';

		return domainToASCII(hostname) + port;
	}

	@bindThis
	public toPunyNullable(host: string | null | undefined): string | null {
		if (host == null) return null;
		return this.toPuny(host);
	}

	@bindThis
	public punyHost(url: string): string {
		const urlObj = new URL(url);
		const host = `${this.toPuny(urlObj.hostname)}${urlObj.port.length > 0 ? ':' + urlObj.port : ''}`;
		return host;
	}

	@bindThis
	private specialSuffix(hostname: string): string | null {
		// masto.host provides domain names for its clients, we have to
		// treat it as if it were a public suffix
		const mastoHost = hostname.match(/\.?([a-zA-Z0-9-]+\.masto\.host)$/i);
		if (mastoHost) {
			return mastoHost[1];
		}

		return null;
	}

	@bindThis
	public punyHostPSLDomain(url: string | URL): string {
		const urlObj = typeof(url) === 'object' ? url : new URL(url);
		const hostname = urlObj.hostname;
		const domain = this.specialSuffix(hostname) ?? psl.get(hostname) ?? hostname;
		const host = `${this.toPuny(domain)}${urlObj.port.length > 0 ? ':' + urlObj.port : ''}`;
		return host;
	}

	@bindThis
	public isFederationAllowedHost(host: string): boolean {
		if (this.meta.federation === 'none') return false;
		if (this.meta.federation === 'specified' && !this.meta.federationHosts.some(x => `.${host.toLowerCase()}`.endsWith(`.${x}`))) return false;
		if (this.isBlockedHost(this.meta.blockedHosts, host)) return false;

		return true;
	}

	@bindThis
	public isFederationAllowedUri(uri: string): boolean {
		const host = this.extractDbHost(uri);
		return this.isFederationAllowedHost(host);
	}

	@bindThis
	public isActiveRemoteUser(user: MiRemoteUser): boolean {
		return !user.isDeleted && !user.isSuspended && this.isFederationAllowedHost(user.host);
	}

	@bindThis
	public assertActiveRemoteUser(user: MiRemoteUser): void {
		if (user.isDeleted) {
			throw new IdentifiableError(errorCodes.userDeleted, `User ${user.id} @${user.username}@${user.host} (${user.uri}) is deleted`);
		}
		if (user.isSuspended) {
			throw new IdentifiableError(errorCodes.userSuspended, `User ${user.id} @${user.username}@${user.host} (${user.uri}) is suspended`);
		}
		if (!this.isFederationAllowedHost(user.host)) {
			throw new IdentifiableError(errorCodes.federationNotAllowed, `User ${user.id} @${user.username}@${user.host} (${user.uri}) is defederated`);
		}
	}

	@bindThis
	public isActiveLocalUser(user: MiLocalUser): boolean {
		return !user.isDeleted && !user.isSuspended && user.approved;
	}

	@bindThis
	public assertActiveLocalUser(user: MiLocalUser): void {
		if (user.isDeleted) {
			throw new IdentifiableError(errorCodes.userDeleted, `User ${user.id} @${user.username} is deleted`);
		}
		if (user.isSuspended) {
			throw new IdentifiableError(errorCodes.userSuspended, `User ${user.id} @${user.username} is suspended`);
		}
		if (!user.approved && this.meta.approvalRequiredForSignup) {
			throw new IdentifiableError(errorCodes.userNotApproved, `User ${user.id} @${user.username} is not approved`);
		}
	}

	@bindThis
	public isActiveUser(user: MiUser | MiLocalUser | MiRemoteUser): boolean {
		if (isRemoteUser(user)) {
			return this.isActiveRemoteUser(user);
		} else if (isLocalUser(user)) {
			return this.isActiveLocalUser(user);
		} else {
			return false;
		}
	}

	@bindThis
	public assertActiveUser(user: MiUser | MiLocalUser | MiRemoteUser): void {
		if (isRemoteUser(user)) {
			this.assertActiveRemoteUser(user);
		} else if (isLocalUser(user)) {
			this.assertActiveLocalUser(user);
		} else {
			throw new IdentifiableError(errorCodes.assertionFailed, `User ${user.id} is malformed - both isRemoteUser and isLocalUser returned false. This is a critical bug, please report it immediately!`);
		}
	}

	@bindThis
	public getUrlScheme(url: string): string {
		try {
			// Returns in the format "https:" or an empty string
			return new URL(url).protocol;
		} catch {
			return '';
		}
	}

	@bindThis
	public isDeliverSuspendedSoftware(software: Pick<MiInstance, 'softwareName' | 'softwareVersion'>): SoftwareSuspension | undefined {
		// a missing name or version is treated as the empty string
		const softwareName = software.softwareName ?? '';
		const softwareVersion = software.softwareVersion ?? '';

		function maybeRegexpMatch(test: string, target: string): boolean {
			const regexpStrPair = test.trim().match(/^\/(.+)\/(.*)$/);
			if (!regexpStrPair) return false; // not a regexp, can't match

			try {
				return new RE2(regexpStrPair[1], regexpStrPair[2]).test(target);
			} catch (err) {
				return false; // not a well-formed regexp, can't match
			}
		}

		// each element of `meta.deliverSuspendedSoftware` can have a
		// normal string, a `*`, or a `/regexp/` for software or
		// versionRange
		return this.meta.deliverSuspendedSoftware.find(
			x => (
				(
					x.software.trim() === '*' ||
						x.software === softwareName ||
						maybeRegexpMatch(x.software, softwareName)
				) && (
					x.versionRange.trim() === '*' ||
						semver.satisfies(softwareVersion, x.versionRange, { includePrerelease: true }) ||
						maybeRegexpMatch(x.versionRange, softwareVersion)
				)
			)
		);
	}

	/**
	 * Verifies that a provided URL is in a format acceptable for federation.
	 * @throws {IdentifiableError} If URL cannot be parsed
	 * @throws {IdentifiableError} If URL is not HTTPS (or HTTP, if allowed)
	 * @throws {IdentifiableError} If URL contains a fragment (if not allowed)
	 * @throws {IdentifiableError} If URL contains credentials
	 */
	@bindThis
	public assertUrl(url: string | URL, opts?: { allowHttp?: boolean, allowFragment?: boolean }): URL | never {
		const allowHttp = opts?.allowHttp ?? false;
		const allowFragment = opts?.allowFragment ?? true;

		// If string, parse and validate
		if (typeof(url) === 'string') {
			try {
				url = new URL(url);
			} catch {
				throw new IdentifiableError(errorCodes.urlValidationFailed, `invalid url ${url}: not a valid URL`);
			}
		}

		// Must be HTTPS
		if (!this.checkHttps(url, allowHttp)) {
			throw new IdentifiableError(errorCodes.urlValidationFailed, `invalid url ${url}: unsupported protocol ${url.protocol}`);
		}

		// Must not have credentials
		if (url.username || url.password) {
			throw new IdentifiableError(errorCodes.urlValidationFailed, `invalid url ${url}: contains embedded credentials`);
		}

		// Must not have a fragment (hash)
		if (url.hash && !allowFragment) {
			throw new IdentifiableError(errorCodes.urlValidationFailed, `invalid url ${url}: contains a fragment component (hash)`);
		}

		return url;
	}

	/**
	 * Verifies that a provided URL is in a format acceptable for federation.
	 */
	public isValidUrl(url: string | URL, opts?: { allowHttp?: boolean, allowFragment?: boolean }): boolean {
		try {
			this.assertUrl(url, opts);
			return true;
		} catch {
			return false;
		}
	}

	/**
	 * Checks if the URL contains HTTPS.
	 * Additionally, allows HTTP in non-production environments.
	 * Based on check-https.ts.
	 */
	@bindThis
	public checkHttps(url: string | URL, allowHttp = false): boolean {
		const isNonProd = this.envService.env.NODE_ENV !== 'production';

		try {
			const proto = new URL(url).protocol;
			return proto === 'https:' || (proto === 'http:' && (isNonProd || allowHttp));
		} catch {
			// Invalid URLs don't "count" as HTTPS
			return false;
		}
	}

	// Moved from ApPersonService to avoid circular dependency
	@bindThis
	public parseUri(value: string | IObject | [string | IObject]): UriParseResult {
		const separator = '/';

		const apId = getApId(value);
		const uri = new URL(apId);
		if (this.toPuny(uri.host) !== this.toPuny(this.config.host)) {
			return { local: false, uri: apId };
		}

		const [, type, id, ...rest] = uri.pathname.split(separator);
		return {
			local: true,
			type,
			id,
			rest: rest.length === 0 ? undefined : rest.join(separator),
		};
	}

	/**
	 * Parses an input Acct into username and normalized host.
	 * @param input Parsed or stringified Acct input
	 * @param usernameLower If true (default), then username will be lowercased. Host is always lowercased.
	 * @param selfHost How to interpret a null host
	 */
	@bindThis
	public parseAcct(input: string | Acct.Acct, usernameLower = true, selfHost: string | null = null): Acct.Acct {
		const acct = typeof(input) === 'string' ? Acct.parse(input, false) : input;

		const dbHost = this.toPunyNullable(acct.host ?? selfHost);
		const host = dbHost === this.punyConfigHost ? null : dbHost;

		const username = usernameLower
			? acct.username.toLowerCase()
			: acct.username;

		return { username, host };
	}

	@bindThis
	public stringifyAcct(input: string | Acct.Acct): string {
		const acct = this.parseAcct(input);
		return Acct.toString(acct);
	}
}
