name: Publish Docker image (develop)

on:
  push:
    branches:
      - develop
    paths:
      - packages/**
      - locales/**
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  push_to_registry:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    if: github.repository == 'transfem-org/Sharkey'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Check out the repo
        uses: actions/checkout@v4.1.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0
        with:
          platforms: linux/amd64,linux/arm64
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/transfem-org/sharkey
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to GHCR
        id: build
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          provenance: false
          tags:  ${{ env.REGISTRY }}/transfem-org/sharkey:develop
          labels: develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Push update to server
        if: steps.build.outcome == 'success'
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.AUTO_UPDATE_DEV_URL }}
          method: POST
          timeout: 600000
